### PR TITLE
FUSETOOLS-2564 - fixed broken dependency loading

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by lhein** [comment]
@bfitzpat I took another attempt to fix your original PR. It seems Eclipse is clever enough to handle the re-export itself. That makes the whole felix bundle plugin wrapping logic obsolete imo.
I am able to build both from inside the bundle and also from the project root. The integration tests are succeeding on my machine too. I then installed Eclipse + DevStudio and installed the locally built update site into it. Then I ran the wizard with the test wsdl from the integration test and that seemed to work well. I suggest you try all of the above and any additional scenarios u can imagine on your machine too. This would be definitely a cleaner solution than the other PR #33 and hence I would prefer to use this PR. Waiting for your feedback.

**Comment by bfitzpat** [comment]
This seems to be close to what we want, but not quite. I had to add a few things.

Though it builds in maven, it doesn't run in Eclipse for me. I was able to kick off the integration tests from maven however by going into fuseide\editor\tests\org.fusesource.ide.wsdl2rest.ui.tests.integration after doing a mvn clean verify -DskipTests at the root and then doing a simple "mvn install" in the test directory. 

to *wsdl2rest.ui I added this to the MANIFEST.MF (the x-friends):
```
Export-Package: 
 org.fusesource.ide.wsdl2rest.ui.internal;x-friends:="org.fusesource.ide.wsdl2rest.ui.tests.integration",
 org.fusesource.ide.wsdl2rest.ui.wizard;x-friends:="org.fusesource.ide.wsdl2rest.ui.tests.integration",
 org.fusesource.ide.wsdl2rest.ui.wizard.pages;x-friends:="org.fusesource.ide.wsdl2rest.ui.tests.integration"
```

That got me a bit further. But I'm still getting some funky errors when trying to get the tests to run (and the wizard doesn't even load for me in my runtime environment right now). 

This is a log of the unit test run
[log.txt](https://github.com/bfitzpat/fuseide/files/1985850/log.txt)

**Comment by bfitzpat** [comment]
So I think we're close, but not quite. So I'm hopeful we can beat this into submission tomorrow @lhein

**Comment by lhein** [comment]
That sounds very weird. The IT only uses the wizard package and that is already exported, no need to limit the exported packages visibility imo. I think your problem lies somewhere else.

**Pull request merged**
