### PR TITLE
fix the swt / cocoa lib failures from CI

### PR DESCRIPTION
**Pull request by lhein**

### CODE REVIEW

**Comment by lhein** [comment]
@bfitzpat this one should the native lib issue from the CI

**Comment by lhein** [comment]
@bfitzpat this one will fix the model issue

**Comment by lhein** [comment]
btw. I think we will run into an issue with the SAP global config element as it also uses beans. We should test it carefully.

**Review by bfitzpat — APPROVED** [review]

**Comment by bfitzpat** [comment]
Thanks for the PR -- checking it out today.

**Pull request merged**
